spring.datasource.url=jdbc:postgresql://localhost:5432/gs_website
spring.datasource.username=gs_admin
spring.datasource.password=gs_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true